services:
  # Backend
  backend:
    build:
      context: ./apps/backend
      dockerfile: Dockerfile
    container_name: uptime-api
    environment:
      DATABASE_URL: 'postgresql://ZulFix:93403150@db:5432/uptime_db?schema=public'
      REDIS_HOST: 'redis'
      REDIS_PORT: 6379
    depends_on:
      - db
      - redis
    ports:
      - '5000:5000'
    volumes:
      - ./apps/backend:/app
      - /app/node_modules
    command: npm run start:dev

  # Frontend
  frontend:
    build:
      context: ./apps/frontend
      dockerfile: Dockerfile
    container_name: uptime-ui
    environment:
      NEXT_PUBLIC_API_URL: 'http://localhost:5000'
    depends_on:
      backend:
        condition: service_started
    ports:
      - '3000:3000'
    volumes:
      - ./apps/frontend:/app
      - /app/node_modules
    command: npm run dev

  # Database
  db:
    image: postgres:15-alpine
    container_name: uptime-db
    environment:
      POSTGRES_USER: ZulFix
      POSTGRES_PASSWORD: 93403150
      POSTGRES_DB: uptime_db
    ports:
      - '5432:5432'
    volumes:
      - db_data:/var/lib/postgresql/data

  # Redis
  redis:
    image: redis:alpine
    container_name: uptime-redis
    ports:
      - '6379:6379'

  # PgAdmin
  pgadmin:
    image: dpage/pgadmin4:latest
    container_name: uptime-pgadmin
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@local.com
      PGADMIN_DEFAULT_PASSWORD: admin
    ports:
      - '5050:80'
    depends_on:
      - db
volumes:
  frontend_node_modules:
  db_data:
