services:
  # Backend
  backend:
    build:
      context: ./apps/backend
      dockerfile: Dockerfile
    container_name: uptime-api
    networks:
      - monitor-network
    environment:
      DATABASE_URL: 'postgresql://ZulFix:93403150@db:5432/uptime_db?schema=public'
      REDIS_HOST: 'redis'
      REDIS_PORT: 6379
      JWT_SECRET: '4a8ca18dba70e17f342f7416f8ad516d797ee0ac'
      FRONTEND_URL: 'http://localhost:3000'
      PORT: 5000
    depends_on:
      - db
      - redis
    ports:
      - '5000:5000'
    volumes:
      - ./apps/backend:/app
      - /app/node_modules
    command: npm run start:dev

  # Frontend
  frontend:
    build:
      context: ./apps/frontend
      dockerfile: Dockerfile
    container_name: uptime-ui
    networks:
      - monitor-network
    environment:
      # ВАЖНО: Для браузера это localhost, для Cypress внутри сети — имя сервиса
      NEXT_PUBLIC_API_URL: http://localhost:5000
    depends_on:
      backend:
        condition: service_started
    ports:
      - '3000:3000'
    volumes:
      - ./apps/frontend:/app
      - /app/node_modules
    healthcheck:
      test:
        [
          'CMD',
          'node',
          '-e',
          "require('http').get('http://localhost:3000', r => process.exit(r.statusCode === 200 ? 0 : 1)).on('error', () => process.exit(1))",
        ]
      interval: 5s
      timeout: 3s
      retries: 30
      start_period: 30s
    command: sh -c "npm run dev"

  # Database
  db:
    image: postgres:15-alpine
    container_name: uptime-db
    networks:
      - monitor-network
    environment:
      POSTGRES_USER: ZulFix
      POSTGRES_PASSWORD: 93403150
      POSTGRES_DB: uptime_db
    ports:
      - '5432:5432'
    volumes:
      - db_data:/var/lib/postgresql/data

  # Redis
  redis:
    image: redis:alpine
    container_name: uptime-redis
    networks:
      - monitor-network
    ports:
      - '6379:6379'

  # Cypress
  # cypress:
  #   build:
  #     context: ./apps/frontend # Исправлен путь к контексту
  #     dockerfile: Dockerfile.cypress
  #   container_name: uptime-cypress
  #   networks:
  #     - monitor-network
  #   environment:
  #     - CYPRESS_baseUrl=http://frontend:3000
  #     - NEXT_PUBLIC_API_URL=http://backend:5000
  #   depends_on:
  #     frontend:
  #       condition: service_healthy
  #     backend:
  #       condition: service_started

volumes:
  db_data:

networks:
  monitor-network:
    driver: bridge
